package common.model;

public class PlantDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plant_dict.id
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plant_dict.name
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plant_dict.code
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plant_dict.type
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plant_dict.id
     *
     * @return the value of plant_dict.id
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plant_dict.id
     *
     * @param id the value for plant_dict.id
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plant_dict.name
     *
     * @return the value of plant_dict.name
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plant_dict.name
     *
     * @param name the value for plant_dict.name
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plant_dict.code
     *
     * @return the value of plant_dict.code
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plant_dict.code
     *
     * @param code the value for plant_dict.code
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plant_dict.type
     *
     * @return the value of plant_dict.type
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plant_dict.type
     *
     * @param type the value for plant_dict.type
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}