package common.model;

import java.util.Date;

public class PlantDoor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.code
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.terrace
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String terrace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.x
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String x;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.z
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String z;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.y
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String y;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.port
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String port;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.user_name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.address_url
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String addressUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.status
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.pid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String fid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.location
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_door.region_id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String regionId;

	private Date inTime = new Date();
	public Date getInTime() {
		return inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.id
	 * @return  the value of plant_door.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.id
	 * @param id  the value for plant_door.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.name
	 * @return  the value of plant_door.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.name
	 * @param name  the value for plant_door.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.code
	 * @return  the value of plant_door.code
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.code
	 * @param code  the value for plant_door.code
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.type
	 * @return  the value of plant_door.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.type
	 * @param type  the value for plant_door.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.terrace
	 * @return  the value of plant_door.terrace
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getTerrace() {
		return terrace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.terrace
	 * @param terrace  the value for plant_door.terrace
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setTerrace(String terrace) {
		this.terrace = terrace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.x
	 * @return  the value of plant_door.x
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getX() {
		return x;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.x
	 * @param x  the value for plant_door.x
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setX(String x) {
		this.x = x;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.z
	 * @return  the value of plant_door.z
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getZ() {
		return z;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.z
	 * @param z  the value for plant_door.z
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setZ(String z) {
		this.z = z;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.y
	 * @return  the value of plant_door.y
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getY() {
		return y;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.y
	 * @param y  the value for plant_door.y
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setY(String y) {
		this.y = y;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.port
	 * @return  the value of plant_door.port
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getPort() {
		return port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.port
	 * @param port  the value for plant_door.port
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setPort(String port) {
		this.port = port;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.user_name
	 * @return  the value of plant_door.user_name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.user_name
	 * @param userName  the value for plant_door.user_name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.address_url
	 * @return  the value of plant_door.address_url
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getAddressUrl() {
		return addressUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.address_url
	 * @param addressUrl  the value for plant_door.address_url
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setAddressUrl(String addressUrl) {
		this.addressUrl = addressUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.status
	 * @return  the value of plant_door.status
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.status
	 * @param status  the value for plant_door.status
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.pid
	 * @return  the value of plant_door.pid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.pid
	 * @param pid  the value for plant_door.pid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.fid
	 * @return  the value of plant_door.fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.fid
	 * @param fid  the value for plant_door.fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setFid(String fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.location
	 * @return  the value of plant_door.location
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.location
	 * @param location  the value for plant_door.location
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_door.region_id
	 * @return  the value of plant_door.region_id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getRegionId() {
		return regionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_door.region_id
	 * @param regionId  the value for plant_door.region_id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}
}