package common.model;

import java.util.Date;

public class PlantTel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.number
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.sn
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String sn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.position
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.level
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.ip
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.mac
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String mac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.org_fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String orgFid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.super_fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String superFid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.model
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String model;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.deleted
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private Integer deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.pid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String fid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.location
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column plant_tel.region_id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String regionId;
	private Integer status;
	private String code;
	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	private Date inTime = new Date();
	public Date getInTime() {
		return inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.id
	 * @return  the value of plant_tel.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.id
	 * @param id  the value for plant_tel.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.number
	 * @return  the value of plant_tel.number
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.number
	 * @param number  the value for plant_tel.number
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setNumber(String number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.name
	 * @return  the value of plant_tel.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.name
	 * @param name  the value for plant_tel.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.sn
	 * @return  the value of plant_tel.sn
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.sn
	 * @param sn  the value for plant_tel.sn
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setSn(String sn) {
		this.sn = sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.position
	 * @return  the value of plant_tel.position
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.position
	 * @param position  the value for plant_tel.position
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.type
	 * @return  the value of plant_tel.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.type
	 * @param type  the value for plant_tel.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.level
	 * @return  the value of plant_tel.level
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.level
	 * @param level  the value for plant_tel.level
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.ip
	 * @return  the value of plant_tel.ip
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.ip
	 * @param ip  the value for plant_tel.ip
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.mac
	 * @return  the value of plant_tel.mac
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getMac() {
		return mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.mac
	 * @param mac  the value for plant_tel.mac
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setMac(String mac) {
		this.mac = mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.org_fid
	 * @return  the value of plant_tel.org_fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getOrgFid() {
		return orgFid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.org_fid
	 * @param orgFid  the value for plant_tel.org_fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setOrgFid(String orgFid) {
		this.orgFid = orgFid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.super_fid
	 * @return  the value of plant_tel.super_fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getSuperFid() {
		return superFid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.super_fid
	 * @param superFid  the value for plant_tel.super_fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setSuperFid(String superFid) {
		this.superFid = superFid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.model
	 * @return  the value of plant_tel.model
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getModel() {
		return model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.model
	 * @param model  the value for plant_tel.model
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.deleted
	 * @return  the value of plant_tel.deleted
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public Integer getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.deleted
	 * @param deleted  the value for plant_tel.deleted
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.pid
	 * @return  the value of plant_tel.pid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.pid
	 * @param pid  the value for plant_tel.pid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.fid
	 * @return  the value of plant_tel.fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.fid
	 * @param fid  the value for plant_tel.fid
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setFid(String fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.location
	 * @return  the value of plant_tel.location
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.location
	 * @param location  the value for plant_tel.location
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column plant_tel.region_id
	 * @return  the value of plant_tel.region_id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getRegionId() {
		return regionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column plant_tel.region_id
	 * @param regionId  the value for plant_tel.region_id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}
}