package common.model;

import java.util.Date;

public class PlantRunningStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plant_running_status.fid
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plant_running_status.status
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plant_running_status.in_time
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    private Date inTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plant_running_status.fid
     *
     * @return the value of plant_running_status.fid
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plant_running_status.fid
     *
     * @param fid the value for plant_running_status.fid
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plant_running_status.status
     *
     * @return the value of plant_running_status.status
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plant_running_status.status
     *
     * @param status the value for plant_running_status.status
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plant_running_status.in_time
     *
     * @return the value of plant_running_status.in_time
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plant_running_status.in_time
     *
     * @param inTime the value for plant_running_status.in_time
     *
     * @mbggenerated Fri Aug 04 16:15:45 CST 2017
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
}