package common.model;

public class SecService {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_service.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_service.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_service.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_service.prison
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String prison;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_service.id
	 * @return  the value of sec_service.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String Info;
	private String Introduction;
	private String Description;
	private String Demo;
	
	public String getInfo() {
		return Info;
	}

	public void setInfo(String info) {
		Info = info;
	}

	public String getIntroduction() {
		return Introduction;
	}

	public void setIntroduction(String introduction) {
		Introduction = introduction;
	}

	public String getDescription() {
		return Description;
	}

	public void setDescription(String description) {
		Description = description;
	}

	public String getDemo() {
		return Demo;
	}

	public void setDemo(String demo) {
		Demo = demo;
	}

	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_service.id
	 * @param id  the value for sec_service.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_service.name
	 * @return  the value of sec_service.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_service.name
	 * @param name  the value for sec_service.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_service.type
	 * @return  the value of sec_service.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_service.type
	 * @param type  the value for sec_service.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_service.prison
	 * @return  the value of sec_service.prison
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getPrison() {
		return prison;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_service.prison
	 * @param prison  the value for sec_service.prison
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setPrison(String prison) {
		this.prison = prison;
	}
}