package common.model;

public class SecStandard {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_standard.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_standard.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_standard.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sec_standard.description
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_standard.id
	 * @return  the value of sec_standard.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_standard.id
	 * @param id  the value for sec_standard.id
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_standard.type
	 * @return  the value of sec_standard.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_standard.type
	 * @param type  the value for sec_standard.type
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_standard.name
	 * @return  the value of sec_standard.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_standard.name
	 * @param name  the value for sec_standard.name
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sec_standard.description
	 * @return  the value of sec_standard.description
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sec_standard.description
	 * @param description  the value for sec_standard.description
	 * @mbggenerated  Fri Aug 04 16:15:45 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}